In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('train.txt', unpack=True)
x_data = xy[0:-1]
y_data = xy[-1]

In [6]:
X = tf.placeholder(tf.float32, [3, None])
Y = tf.placeholder(tf.float32)

In [4]:
W1 = tf.Variable(tf.random_uniform([2, 3], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0))
b2 = tf.Variable(tf.zeros([1]))

In [7]:
l1 = tf.div(1., 1. + tf.exp( - (tf.matmul(W1, X))))
y_ = tf.div(1., 1. + tf.exp( - (tf.matmul(W2, l1) + b2)))

In [8]:
cost = -tf.reduce_mean(Y * tf.log(y_) + (1-Y) * tf.log(1-y_))
alpha = 0.1
optimizer = tf.train.GradientDescentOptimizer(alpha)
train = optimizer.minimize(cost)


In [9]:
init = tf.initialize_all_variables()

In [12]:
sess = tf.InteractiveSession()
sess.run(init)

In [11]:
for step in range(1001):
    cost_val, weight1_val, weight2_val, _ = sess.run([cost, W1, W2, train], feed_dict = {X:x_data, Y:y_data})
    if (step % 20 == 0):
        print(step, cost_val, weight1_val, weight2_val)
correct_prediction = tf.equal(tf.floor(y_ + 0.5), Y)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))
print(sess.run([y_, tf.floor(y_ + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data}))

0 0.718882 [[ 0.04971357 -0.07946226 -0.3087005 ]
 [-0.93455267  0.66948116 -0.76274854]] [[-0.81964129 -0.20690806]]
20 0.700254 [[ 0.01883223 -0.09627593 -0.32224286]
 [-0.93923432  0.6640079  -0.76193106]] [[-0.74751472 -0.15033202]]
40 0.695389 [[ 0.00401745 -0.10509636 -0.32824451]
 [-0.94070339  0.66108882 -0.76049614]] [[-0.71170586 -0.11607584]]
60 0.694078 [[-0.00342324 -0.11023265 -0.33084327]
 [-0.94104433  0.6592654  -0.75904018]] [[-0.69399953 -0.09324441]]
80 0.693687 [[-0.0073238  -0.11358526 -0.33183861]
 [-0.94098371  0.65798521 -0.75772667]] [[-0.68540531 -0.07627276]]
100 0.693537 [[-0.00947732 -0.11604282 -0.33206621]
 [-0.94079286  0.65702218 -0.7565974 ]] [[-0.68143362 -0.06233017]]
120 0.69345 [[-0.01075702 -0.1180382  -0.33193135]
 [-0.940579    0.65627807 -0.75566006]] [[-0.67981929 -0.04997199]]
140 0.693381 [[-0.01159846 -0.11978747 -0.33163571]
 [-0.94038612  0.6557076  -0.75491321]] [[-0.67941147 -0.03845778]]
160 0.693317 [[-0.01222168 -0.12140003 -0.33128

In [20]:
print(W1.get_shape())
print(X.get_shape())
print(l1.get_shape())
print(W2.get_shape())
print(b2.get_shape())
print(y_.get_shape())

print(sess.run(b2))
print(cost)

(2, 3)
(3, ?)
(2, ?)
(1, 2)
(1,)
(1, ?)
[ 0.]
Tensor("Neg_2:0", dtype=float32)


In [ ]:
sess.close()