In [1]:
import tensorflow as tf
import numpy as np

In [17]:
x_data = [[1., 1., 1., 1., 1., 1., 1., 1.],
          [2., 3., 3., 5., 7., 2., 6., 7.],
          [1., 2., 4., 5., 5., 5., 6., 7.]]
y_data = [[0., 0., 0., 0., 0., 0., 1., 1.],
          [0., 0., 0., 1., 1., 1., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0., 0.]]

In [4]:
print(x_data)
print(y_data)

[[1, 1, 1, 1, 1, 1, 1, 1], [2, 3, 3, 5, 7, 2, 6, 7], [1, 2, 4, 5, 5, 5, 6, 7]]
[[0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 1, 1, 1, 0, 0], [1, 1, 1, 0, 0, 0, 0, 0]]


In [6]:
weight = [[ 0.84378982, -0.63257223,  0.84004235],
          [ 0.19547772, -0.4945803,   0.56019384],
          [-0.84074593, -0.09886688,  0.26566958]]

In [18]:
tf_x = tf.constant(x_data)
tf_y = tf.constant(y_data)
tf_w = tf.constant(weight)

In [14]:
sess = tf.InteractiveSession()

In [19]:
print(sess.run(tf_x))
print(sess.run(tf_y))
print(sess.run(tf_w))

[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  7.  2.  6.  7.]
 [ 1.  2.  4.  5.  5.  5.  6.  7.]]
[[ 0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.]]
[[ 0.84378982 -0.63257223  0.84004235]
 [ 0.19547772 -0.4945803   0.56019384]
 [-0.84074593 -0.09886688  0.26566958]]


In [36]:
print(tf_x.get_shape())

(3, 8)


In [24]:
mult = sess.run(tf.matmul(tf_w, tf_x))
print(mult)

[[ 0.4186877   0.62615776  2.30624247  1.88114023  0.61599565  3.77885675
   2.08861041  2.29608083]
 [-0.23348904 -0.16787553  0.95251215  0.52354527 -0.46561527  2.00728631
   0.58915901  0.65477252]
 [-0.7728101  -0.60600734 -0.07466817 -0.00673246 -0.2044661   0.28986824
   0.1600703   0.32687306]]


In [35]:
softm = sess.run(tf.nn.softmax(mult, dim=0))
print(softm)

[[ 0.5480423   0.57350022  0.74033415  0.70988828  0.56202596  0.8329187
   0.73066688  0.75002223]
 [ 0.2854811   0.2592324   0.19120981  0.18263921  0.19055429  0.1416509
   0.16312328  0.14529912]
 [ 0.16647659  0.16726732  0.06845599  0.10747249  0.24741976  0.02543046
   0.10620993  0.10467863]]


In [47]:
costm = sess.run(- tf_y * tf.log(softm))
print(costm)

[[ 0.          0.          0.          0.          0.          0.
   0.31379765  0.28765243]
 [ 0.          0.          0.          1.70024252  1.65781808  1.95438969
   0.          0.        ]
 [ 1.79290056  1.78816199  2.68156433  0.          0.          0.          0.
   0.        ]]


In [48]:
sess.run(tf.reduce_sum(costm, 0))

array([ 1.79290056,  1.78816199,  2.68156433,  1.70024252,  1.65781808,
        1.95438969,  0.31379765,  0.28765243], dtype=float32)

In [49]:
sess.run(tf.reduce_mean(tf.reduce_sum(costm, 0)))

1.522066

In [27]:
softm = sess.run(tf.nn.softmax(tf.transpose(mult)))
print(softm)

[[ 0.5480423   0.2854811   0.16647659]
 [ 0.57350022  0.2592324   0.16726732]
 [ 0.74033415  0.19120981  0.06845599]
 [ 0.70988828  0.18263921  0.10747249]
 [ 0.56202596  0.19055429  0.24741976]
 [ 0.8329187   0.1416509   0.02543046]
 [ 0.73066688  0.16312328  0.10620993]
 [ 0.75002223  0.14529912  0.10467863]]


In [23]:
0.19547772 * 1 + (-0.4945803) * 2 + 0.56019384 * 1

-0.23348903999999993

In [31]:
0.01817829 + 0.02236949 + 0.12003493 + 0.07846718 + 0.02214332 + 0.52342671 + 0.09655866 + 0.11882135

0.99999993

In [32]:
0.5480423 +  0.2854811 +  0.16647659

0.9999999900000001